version: "3.8"

services:
  kong-database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${DB_PASSWORD} # REQUIRED: Must be set in .env
      POSTGRES_DB: kong
    volumes:
      - kong-database-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    command:
      [
        "postgres",
        "-c",
        "max_connections=200",
        "-c",
        "shared_preload_libraries=pg_stat_statements",
      ]
    networks:
      - kong-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/run/postgresql

  kong-migration:
    image: kong:3.7
    command: kong migrations bootstrap
    user: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${DB_PASSWORD}
      KONG_PG_DATABASE: kong
      KONG_LOG_LEVEL: notice
    depends_on:
      kong-database:
        condition: service_healthy
    networks:
      - kong-net
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"

  kong:
    image: kong:3.7
    user: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${DB_PASSWORD}
      KONG_PG_DATABASE: kong

      # Production logging
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: notice

      # Admin interface configuration
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002
      KONG_ADMIN_GUI_URL: http://127.0.0.1:8002
      KONG_ADMIN_API_URI: http://localhost:8001

      # Production security settings
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_SESSION_SECRET: ${KONG_SESSION_SECRET}
      KONG_ADMIN_GUI_AUTH_CONF: '{"admin": {"password": "${KONG_ADMIN_PASSWORD}"}}'

      # SSL and proxy settings - Updated for standard ports
      KONG_PROXY_LISTEN: 0.0.0.0:3000, 0.0.0.0:3001 ssl

      # SSL certificate configuration
      # KONG_SSL_CERT: /etc/kong/ssl/kong.roots.co.id.crt
      # KONG_SSL_CERT_KEY: /etc/kong/ssl/kong.roots.co.id.key

      # Performance settings
      KONG_NGINX_WORKER_PROCESSES: auto
      KONG_NGINX_WORKER_CONNECTIONS: 2048

      # Production trusted IPs - CUSTOMIZE for your infrastructure
      # KONG_REAL_IP_HEADER: X-Forwarded-For
      # KONG_TRUSTED_IPS: 172.16.0.0/12,10.0.0.0/8,192.168.0.0/16

      # Cloudflare specific headers
      KONG_REAL_IP_HEADER: CF-Connecting-IP
      KONG_TRUSTED_IPS: 173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22

    ports:
      # Standard HTTP/HTTPS ports
      - "80:3000" # HTTP proxy port
      - "443:3001" # HTTPS proxy port

      # Admin ports - bind ke localhost untuk security
      - "127.0.0.1:8001:8001" # Admin API (hanya localhost)
      - "127.0.0.1:8002:8002" # Admin GUI (hanya localhost)

    volumes:
      # Mount SSL certificates
      - ./ssl:/etc/kong/ssl:ro

    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_completed_successfully
    networks:
      - kong-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "2.0"
        reservations:
          memory: 1G
          cpus: "1.0"
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

volumes:
  kong-database-data:
    driver: local

networks:
  kong-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
