version: "3.8"

services:
  kong-database-dev:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${DB_PASSWORD:-kong_dev_password}
      POSTGRES_DB: kong
      # Simplified auth for development
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=trust"
    volumes:
      - kong-database-dev-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    command: ["postgres", "-c", "max_connections=200"]
    ports:
      # Expose database port for development debugging
      - "5433:5432" # Development database port
    networks:
      - kong-net-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kong-migration-dev:
    image: kong:3.7
    command: kong migrations bootstrap
    user: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database-dev
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${DB_PASSWORD:-kong_dev_password}
      KONG_PG_DATABASE: kong
      # Debug level for development
      KONG_LOG_LEVEL: debug
    depends_on:
      kong-database-dev:
        condition: service_healthy
    networks:
      - kong-net-dev
    restart: on-failure

  kong-dev:
    image: kong:3.7
    user: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database-dev
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${DB_PASSWORD:-kong_dev_password}
      KONG_PG_DATABASE: kong

      # Development logging (more verbose)
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug

      # Admin interface - PERBAIKAN KONFIGURASI
      KONG_ADMIN_LISTEN: 0.0.0.0:9001
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:9002 # TAMBAHAN: Missing GUI listen
      KONG_ADMIN_GUI_URL: http://localhost:9002 # PERBAIKAN: Gunakan localhost konsisten
      KONG_ADMIN_API_URI: http://localhost:9001

      # CORS configuration untuk development
      KONG_ADMIN_GUI_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_CORS_ORIGINS: "*"
      KONG_ADMIN_GUI_AUTH_LOGIN_ATTEMPTS: 5

      # Development security (simplified) - PERBAIKAN AUTH CONFIG
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_SESSION_SECRET: ${KONG_SESSION_SECRET:-dev_session_secret}
      # PERBAIKAN: Escape quotes dalam auth config
      KONG_ADMIN_GUI_AUTH_CONF: '{"admin":{"password":"${KONG_ADMIN_PASSWORD:-admin123}"}}'

      # Proxy settings
      KONG_PROXY_LISTEN: 0.0.0.0:4000, 0.0.0.0:4001 ssl

      # Development trusted IPs (more permissive)
      KONG_REAL_IP_HEADER: X-Forwarded-For
      KONG_TRUSTED_IPS: 0.0.0.0/0,::/0

    ports:
      # Proxy ports (different from production)
      - "4000:4000" # HTTP proxy (dev: 4000, prod: 3000)
      - "4001:4001" # HTTPS proxy (dev: 4001, prod: 3001)
      # Admin ports (different from production)
      - "9001:9001" # Admin API (dev: 9001, prod: 8001)
      - "9002:9002" # Admin GUI (dev: 9002, prod: 8002)

    depends_on:
      kong-database-dev:
        condition: service_healthy
      kong-migration-dev:
        condition: service_completed_successfully
    networks:
      - kong-net-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  kong-database-dev-data:
    driver: local

networks:
  kong-net-dev:
    driver: bridge
