version: "3.8"

services:
  kong-database-dev:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${DB_PASSWORD:-kong_dev_password}
      POSTGRES_DB: kong
      # PERBAIKAN: Gunakan auth yang lebih aman
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - kong-database-dev-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    command: ["postgres", "-c", "max_connections=200"]
    # PERBAIKAN: Hapus port exposure database untuk keamanan
    # ports:
    #   - "5433:5432" # REMOVED: Database tidak perlu exposed
    networks:
      - kong-net-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    # PERBAIKAN: Tambah security options
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

  kong-migration-dev:
    image: kong:3.7
    command: kong migrations bootstrap
    user: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database-dev
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${DB_PASSWORD:-kong_dev_password}
      KONG_PG_DATABASE: kong
      # PERBAIKAN: Kurangi log level untuk keamanan
      KONG_LOG_LEVEL: info
    depends_on:
      kong-database-dev:
        condition: service_healthy
    networks:
      - kong-net-dev
    restart: on-failure

  kong-dev:
    image: kong:3.7
    user: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database-dev
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${DB_PASSWORD:-kong_dev_password}
      KONG_PG_DATABASE: kong

      # PERBAIKAN: Logging yang lebih aman
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: info # PERBAIKAN: Kurangi dari debug ke info

      # PERBAIKAN: Admin interface yang lebih aman
      KONG_ADMIN_LISTEN: 0.0.0.0:9001 # PERBAIKAN: Bind ke localhost saja
      # KONG_ADMIN_GUI_LISTEN: 0.0.0.0:9002 # PERBAIKAN: Bind ke localhost saja
      KONG_ADMIN_GUI_URL: http://127.0.0.1:9002 # PERBAIKAN: Gunakan localhost
      KONG_ADMIN_API_URI: http://localhost:9001 # PERBAIKAN: Gunakan localhost

      # PERBAIKAN: CORS yang lebih aman
      KONG_ADMIN_GUI_ACCESS_LOG: /dev/stdout
      # KONG_ADMIN_CORS_ORIGINS: "http://localhost:9002,http://127.0.0.1:9002" # PERBAIKAN: Specific origins
      KONG_ADMIN_GUI_AUTH_LOGIN_ATTEMPTS: 3 # PERBAIKAN: Kurangi login attempts

      # PERBAIKAN: Security yang lebih ketat
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_SESSION_SECRET: ${KONG_SESSION_SECRET:-dev_session_secret}
      KONG_ADMIN_GUI_AUTH_CONF: '{"admin":{"password":"${KONG_ADMIN_PASSWORD:-admin123}"}}'

      # Proxy settings
      KONG_PROXY_LISTEN: 0.0.0.0:4000, 0.0.0.0:4001 ssl

      # PERBAIKAN: Trusted IPs yang lebih aman
      KONG_REAL_IP_HEADER: X-Forwarded-For
      KONG_TRUSTED_IPS: 127.0.0.1,::1,172.16.0.0/12,10.0.0.0/8 # PERBAIKAN: Specific IP ranges

      # PERBAIKAN: Tambah security headers
      KONG_PROXY_ACCESS_LOG_FORMAT: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
      KONG_ADMIN_ACCESS_LOG_FORMAT: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'

    ports:
      # PERBAIKAN: Admin ports hanya bind ke localhost
      - "127.0.0.1:9001:9001" # Admin API (localhost only)
      - "127.0.0.1:9002:9002" # Admin GUI (localhost only)
      # Proxy ports tetap accessible dari luar
      - "4000:4000" # HTTP proxy
      - "4001:4001" # HTTPS proxy

    depends_on:
      kong-database-dev:
        condition: service_healthy
      kong-migration-dev:
        condition: service_completed_successfully
    networks:
      - kong-net-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # PERBAIKAN: Tambah security options
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp

volumes:
  kong-database-dev-data:
    driver: local

networks:
  kong-net-dev:
    driver: bridge
    # PERBAIKAN: Biarkan Docker auto-assign subnet untuk menghindari konflik
